<SporociloWidget>:
    
    orientation: "vertical"
    height: self.minimum_height
    size_hint_y: None

    MDBoxLayout:
        size_hint_x: 1
        adaptive_height: True

        IconLeftWidget:
            icon: "robot-happy-outline"

            size_hint_x: 0.1
            pos_hint: {'center_y': 0.1}
            
        MDLabel:
            max_size_hint_x: 0.5
            pos_hint: {'center_y': 0.5}
            adaptive_height: True
            padding: "4dp"
            halign: "left"

            text: root.odgovor
            theme_text_color: "Custom"
            font_style: "Body1"
            text_color: (245, 40, 145)
        
        Widget:
            size_hint_x: 0.5
    

    MDBoxLayout:
        size_hint_x: 1
        adaptive_height: True
        height: self.height if root.vprasanje else dp(0)
        
        Widget: 
            size_hint_x: 0.5

        MDLabel:
            max_size_hint_x: 0.5
            pos_hint: {'center_y': 0.45}
            adaptive_height: True
            padding: "4dp"
            halign: "right"

            text: root.vprasanje
            theme_text_color: "Custom"
            font_style: "Subtitle1"
            text_color: (64, 128, 64)

        IconRightWidget:
            icon: "account-circle-outline"

            max_size_hint_x: 0.1
            pos_hint: {'center_y': 0.15}
            opacity: 1 if root.vprasanje else 0
