<SporociloWidget>:
    orientation: "vertical"
    size_hint_y: None
    height: self.minimum_height
#     #adaptive_size:
#     adaptive_size: True

#     spacing: dp(4)
#     padding: dp(4)

#     # height: self.minimum_height

#     # size_hint_min_y: self.children[0].texture_size[1]
#     # padding: dp(16)
#     # min_height: self.children[0].texture_size[1] + self.children[1].texture_size[1] + dp(16)
#     # text_size: self.width, None
#     # size_hint_y: None
#     # size_hint: 1, 1
#     # height: self.minimum_height

# #    text_size: self.width, Nonev
#     # height: self.children[0].texture_size[1] + self.children[1].texture_size[1]
    

#     MDLabel:
#         text: root.odgovor
#         # pos_hint: {"top": 1, "left": 1}

#         # valign: "top"
#         outline_width: dp(2)
#         # text_size: self.width, None
#         outline_color: (255, 128, 0, 128)
#         # size_hint_y: None
#         # size_hint_x: 0.4 
#         adaptive_height: True
#         # height: self.texture_size[1]
#         # canvas:
#         #     Color:
#         #         rgba: (0,255,255,255)
#         #     Rectangle:
#         #         pos: self.pos
#         #         size: self.size
#         size_hint_x: 1
#         height: self.texture_size[1]
#         # size_hint_y: 1
#         # text_size: self.width, self.height
#         # height: self.texture_size[1]


#     MDSeparator:

#     MDLabel:
#         # pos_hint: {"bottom": 0, "right": 1}
#         # valign: "bottom"
#         # text_size: self.width, None
#         adaptive_size: True
#         text: root.vprasanje
#         # halign: "right"
#         # adaptive_height: True
#         # theme_text_color: 'Custom'
#         # text_color: (1, 1, 1, 1)
#         size_hint_x: 1
#         # text_size: self.width, self.height
#         # adaptive_height: True
#         height: self.texture_size[1]
#         # size_hint_y: None
#         # size_hint_x: 0.4 
#         #height: self.height
#         #height: self.texture_size[1]
#         # md_bg_color: (1, 0, 1, 0)
#         # md_bg_color: (0, 0, 0, 0)
#         # pos_hint: {'x': 0.5}
        # width: root.width * 0.4  

    # size_hint_y: None
    # height
    # padding: "4dp"
    # radius: 12
    # background_color: "2d4a50"

    MDBoxLayout:
        adaptive_height: True
        size_hint_x: 1
        
        # canvas:
        #     Color:
        #         rgba: 255, 128, 255, 128
        #     Rectangle:
        #         pos: self.pos
        #         size: self.size

        IconLeftWidget:
            icon: "robot-happy-outline"
            size_hint_x: 0.1
            pos_hint: {'center_y': 0.1}

        # IconLeftWidget:
        #     icon: "message-outline"
        #     size_hint_x: 0.1

        # MDIcon:
        #     adaptive_height: True
        #     icon: "gmail"
        #     size_hint_x: 0.2
        #     halign: "right"


        # Widget:
        #     # padding: "4dp"
        #     # size_hint_x: 0.1

        MDLabel:
            text: root.odgovor
            font_style: "Body1"

            theme_text_color: "Custom"
            text_color: (245, 40, 145)

            # bold: True
            max_size_hint_x: 0.5
            pos_hint: {'center_y': 0.5}
            # size_hint_y: 0.5
            halign: "left"
            # pos_hint: {'right': 1}
            padding: "4dp"
            adaptive_height: True
            # size
            # pos_hint: {"center_x": 1}
        
        Widget:
            size_hint_x: 0.5
    

    MDBoxLayout:
        adaptive_height: True
        size_hint_x: 1
        
        height: self.height if root.vprasanje else dp(0)
        # canvas:
        #     Color:
        #         rgba: 255, 128, 255, 128
        #     Rectangle:
        #         pos: self.pos
        #         size: self.size

        # IconRightWidget:
        #     icon: "message-reply-outline"
        #     size_hint_x: 0.1
        
        Widget: 
            size_hint_x: 0.5
        # MDIcon:
        #     adaptive_height: True
        #     icon: "gmail"
        #     size_hint_x: 0.2
        #     halign: "right"


        # Widget:
        #     # padding: "4dp"
        #     # size_hint_x: 0.1

        MDLabel:
            # text: root.odgovor
            text: root.vprasanje
            font_style: "Subtitle1"
            # font_style: "Body1"

            theme_text_color: "Custom"
            # text_color: (245, 40, 145)
            text_color: (64, 128, 64)

            # size_hint_y: 1
            # bold: True
            max_size_hint_x: 0.5
            halign: "right"
            # pos_hint: {'right': 1}
            pos_hint: {'center_y': 0.45}
            padding: "4dp"
            adaptive_height: True
            # size
            # pos_hint: {"center_x": 1}
            # theme_text_color: "Custom"
            
            # theme_text_color: "Hint"
            # adaptive_height: True
            # padding: "4dp"
            # pos_hint: {"center_y": 0}

        # IconRightWidget:
        #     icon: "message-reply-outline"
        #     size_hint_x: 0.1
        
        IconRightWidget:
            icon: "account-circle-outline"
            max_size_hint_x: 0.1
            opacity: 1 if root.vprasanje else 0
            pos_hint: {'center_y': 0.15}


        
    # MDList:

    #     OneLineIconListItem:
    #         height: "84dp"
    #         text: "Edit Profile"
    #         IconLeftWidget:
    #             icon: "account"
    #     OneLineIconListItem:
    #         height: "84dp"
    #         _txt_bot_pad: "32dp"
    #         text: "Call Center"
    #         IconLeftWidget:
    #             icon: "phone"
    #     OneLineIconListItem:
    #         _txt_bot_pad: "32dp"
    #         text: "About Apps"
    #         IconLeftWidget:
    #             icon: "tablet"


    