#:include components/widgets/sporocilo.kv

<PogovorZaslon>:
    name: "pogovorZaslon"
    id: pogovorZaslon

    MDBoxLayout:
        orientation: "vertical"
    
        MDTopAppBar:
            title: "ime pogovora"
            id: pogovor_naslov
            md_bg_color: "#424242"
            specific_text_color: "#F2F2F2"
            right_action_items: 
                [["arrow-left", lambda x: root.zamenjaj_zaslon_pogovori(x), "Nazaj na pogovore"],
                ["pencil", lambda x: root.preimenuj_pogovor(x), "Preimenuj pogovor"],
                ["delete", lambda x: root.prikazi_dialog_zbrisi(x), "Zbrisi pogovor"]]


        MDScrollView:
            id: sporocila_sv

            MDBoxLayout:
                id: sporocila_box

                orientation: "vertical"
                height: self.minimum_height
                adaptive_height: True
                size_hint_x: 1
                padding: "8dp"
                spacing: "4dp"


        MDBoxLayout:
            orientation: "vertical"
            height: dp(72)
            opacity: 0.75
            size_hint_x: 1
            size_hint_y: None

            MDBoxLayout:
                id: vnosni_elementi
                orientation: "horizontal"
                size_hint: 1, 1

                Widget:
                    size_hint_x: 0.05

                MDTextField:
                    id: vnosno_polje
                    mode: "rectangle"
                    hint_text: 'Vnesi svoje sporocilo...'
                    text_color_focus: "white"
                    line_color_focus: "lime"
                    hint_text_color_focus: "yellow"
                    hint_text_color_normal: "lightgreen"

                    size_hint_min_x: 0.85
                    pos_hint: {'center_y': 0.55}

                    on_focus: root.on_keyboard(focus=self.focus)           

                MDIconButton:
                    id: poslji_gumb
                    icon: "send-outline"
                    text_color: "white"
                    height: self.height
                    size_hint: (0.1, 0.75)
                    pos_hint: {'center_y': 0.5}
                    on_release: root.novo_sporocilo()
