<ZacetniZaslon>:
    name: "zacetniZaslon"
    id: zacetniZaslon

    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "GPT pogovori"
            md_bg_color: "#424242"
            specific_text_color: "#F2F2F2"
            pos_hint: {'top': 1}

        MDBoxLayout:
            orientation: "vertical"

            MDLabel:
                id: uvodno_sporocilo
                text: "Ni se pogovorov, ustvari novega?"
                halign: "center"
                             
            MDScrollView:
                size_hint: 1, 1

                MDList:
                    id: pogovori_list
                    size_hint_x: 1
                    
                    padding: dp(8)
                    spacing: dp(4)
           
            MDBoxLayout:
                orientation: "horizontal"
                height: dp(54)
                padding: dp(12) 
                size_hint: 1, None
                
                canvas.before:
                    Color:
                        rgba: (0.2, 0.2, 0.2, 1)
                    Rectangle:
                        size: self.size
                        pos: self.pos

                Widget: 

                MDFillRoundFlatIconButton:
                    icon: "pencil"
                    text: "Zacni nov pogovor"
                    size_hint: None, None
                    pos_hint: {'center_y': 0.5, 'right': 1}
                    on_release: root.zacni_pogovor()