<ZacetniZaslon>:
    name: "zacetniZaslon"
    id: "zacetniZaslon"

    MDBoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: "GPT pogovori"
            elevation: 4
            pos_hint: {"top": 1}
            md_bg_color: "#424242"
            specific_text_color: "#F2F2F2"
            # left_action_items: [["menu", lambda x: app.callback(x)]]


            # MDIconButton:
            #     icon: "information"
            #     pos_hint: {"top": 1, "center_x":0.4}
            #     on_release: app.title_clicked()



        MDBoxLayout:
            orientation: "vertical"

            MDLabel:
                id: uvodno_sporocilo
                # height: dp(0) if root.pogovoriObstajajo else self.height 
                # opacity: 0 if root.pogovoriObstajajo else 1
                 
                halign: "center"
                text: "Ni se pogovorov, ustvari novega?"

            
            ScrollView:
                size_hint: 1, 1

                # height: self.height if root.pogovoriObstajajo else dp(0) 
                # opacity: 1 if root.pogovoriObstajajo else 0
                
                # height: dp(0) if root.pogovoriObstajajo else self.height 
                # opacity: 1 if root.pogovoriObstajajo else 0
                # default_size: 1, dp(72)
                # default_size_hint: 1, None
                MDList:
                    id: pogovori_list
                    # spacing: dp(8)  # Adjust the spacing as needed
                    size_hint_x: 1
                    
                    padding: dp(8)
                    spacing: dp(4)
                    # Populate with existing entries
                    # MDBoxLayout:
                    #     orientation: 'horizontal'
                        
                    #     # size_hint_x: 1
                    #     size_hint_x: 1
                    #     # size_hint_y: 1
                                        


                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"
                    # OneLineListItem:
                    #     text: "Existing Entry 1"
                    #     #secondary_text: "Additional info"
                    #     on_release: app.on_entry_selected("Existing Entry 1")
                    #     # halign: 'right'
                    #     MDBoxLayout:
                    #         # size_hint_x: 1
                    #         width: dp(48)
                    #         pos_hint: {'center_y': 0.5}
                    #         MDCheckbox:
                    #             # right: 1.0
                    #             halign: "right"

           
           
            MDBoxLayout:
                orientation: 'horizontal'
                height: dp(54)
                padding: dp(12)  # Adjust the padding as needed
                size_hint: 1, None
                
                canvas.before:
                    Color:
                        rgba: (0.2, 0.2, 0.2, 1)
                    Rectangle:
                        size: self.size
                        pos: self.pos

                Widget:  # Left empty widget to fill the space on the left

                MDFillRoundFlatIconButton:
                    icon: "pencil"
                    text: "Zacni nov pogovor"
                    # height: self.height
                    # padding: dp(12)
                    # height: "32dp"
                    # on_release: root.create_chat_dialog()
                    on_release: root.zacni_pogovor()
                    # size_hint: 0.25, None
                    # size: self.texture_size
                    size_hint: None, None
                    # size_hint_x: 0.25
                    # halign: "right"
                    # pos_hint: {'right': 1, 'top': 0}
                    pos_hint: {'center_y': 0.5, 'right': 1}
                    # pos_hint: {'center_x': 0.0}
        
        
            # padding: dp(14)


            # height: dp(32)  # Adjust the height as needed

            # Button in the middle for a new entry
            # MDFillRoundFlatIconButton:
            #     icon: "delete"
            #     text: "Zbrisi pogovor"
            #     on_release: app.on_new_entry()
            #     disabled: True
            #     size_hint_y: 1
            # # Spacer
            # Widget:

            # Button in the right bottom corner

                # pos_hint: {'left': 1,'center_y': 0.5}


            # MDRaisedButton:
            #     on_release: root.zacni_pogovor()
